---
repo-name: peripherals-imgur
display-name: imgur
description: Imgur is an image hosting and sharing site, favoured by users of social media and social news sites including Reddit, Twitter and Digg because of its ease of use and flexibility.
